### ISSUE TITLE
Underscores within `<span>` tags inside `<pre><code>` blocks are incorrectly escaped in Markdown output

### ISSUE THREAD

**Issue by stevenhao** [matthewwithanm/python-markdownify#101] opened 2023-12-25 23:55 UTC
### Description
When converting HTML code that includes `<pre><code><span>` structures with underscores inside the `<span>` tags, the `markdownify` package incorrectly escapes the underscores in the resulting Markdown output. This behavior is undesirable when the code blocks are intended to display underscores as literals, which is common in programming for variable names and other identifiers.

### Steps to Reproduce
1. Install `markdownify` version 0.11.6.
2. Run the following Python script:

```python
from markdownify import markdownify as md

html_with_code = '<pre><code><span class="hljs-keyword">variable_name_with_underscores</span></code></pre>'
markdown_output = md(html_with_code)
print(markdown_output)
```

3. Observe the output, which incorrectly escapes the underscores.

### Expected Behavior
The underscores within the `<span>` tags inside the `<pre><code>` blocks should be preserved in the Markdown output as literals, without being escaped.

### Actual Behavior
The underscores are escaped in the Markdown output, resulting in `variable\_name\_with\_underscores` instead of `variable_name_with_underscores`.

### Additional Context
This issue affects the conversion of syntax-highlighted code blocks from HTML to Markdown, where it is crucial to preserve the literal characters of the code. The current behavior could lead to a misrepresentation of the code in the Markdown output.

**Comment by chrispy-snps** [comment] 2024-01-13 13:43
We have this issue too. I will try to come up with a pull request to fix it.

**Comment by chrispy-snps** [comment] 2024-01-14 14:39
This appears to be a duplicate of issue #97.

**Closed** 2024-01-15 20:46 UTC
